/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package stackAndQueue.Node;

public class Node<T> {
    public T data;
    public Node<T> next;

    public Node(T data) {
        this.data= data;
        this.next= null;
    }
}
